export interface MissionDef {
  id: string;
  worldId: string;
  num: number;
  title: string;
  desc: string;
  emoji?: string;
  character: { name: string; role: string; avatar: string; bg: string; text: string; ring: string };
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  duration: string;
  xp: number;
  gradient: string;
  skills: string[];
}

export interface WorldConfig {
  id: string;
  title: string;
  emoji: string;
  worldNumber: number;
  subtitle: string;
  gradient: string;
  glow: string;
  accentColor: string;
  championLabel: string;
  championThreshold: number;
  totalXPLabel: string;
  returnPath: string;
  coachTip: string;
  missions: MissionDef[];
}

export const WORLDS_DATA: Record<string, WorldConfig> = {
  campus: {
    id: 'campus',
    title: 'Campus World',
    emoji: '🎓',
    worldNumber: 1,
    subtitle: 'Master academic communication with Professor Emma. From first introductions to your Final Viva — practice every real campus conversation.',
    gradient: 'from-emerald-600 via-teal-700 to-green-800',
    glow: 'shadow-emerald-500/25',
    accentColor: '#059669',
    championLabel: 'Campus Champion',
    championThreshold: 4,
    totalXPLabel: '1,100 XP',
    returnPath: '/communication/campus',
    coachTip: 'Start with Mission 1 and work your way up. Each mission builds on the previous one. Voice is the primary mode — speak naturally and clearly. Every session generates a unique scenario so no two practice runs are ever the same.',
    missions: [
      {
        id: 'campus_introduce_yourself',
        worldId: 'campus',
        num: 1,
        title: 'Introduce Yourself',
        desc: 'Meet Professor Emma on the first day of class. Introduce yourself naturally — your name, program, goals, and hometown.',
        character: { name: 'Prof. Emma', role: 'University Professor', avatar: '👩‍🏫', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Beginner',
        duration: '5 min',
        xp: 80,
        gradient: 'from-emerald-500 to-teal-600',
        skills: ['Self-introduction', 'Academic tone', 'First impressions'],
      },
      {
        id: 'campus_ask_doubt',
        worldId: 'campus',
        num: 2,
        title: 'Ask a Doubt in Class',
        desc: 'Approach Professor Emma after a lecture on Data Structures to ask a question you were not clear about.',
        character: { name: 'Prof. Emma', role: 'University Professor', avatar: '👩‍🏫', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Beginner',
        duration: '5 min',
        xp: 80,
        gradient: 'from-teal-500 to-emerald-600',
        skills: ['Question framing', 'Technical vocabulary', 'Clarity'],
      },
      {
        id: 'campus_assignment_extension',
        worldId: 'campus',
        num: 3,
        title: 'Request Assignment Extension',
        desc: 'Convince Professor Emma to grant you an extension on an assignment due tomorrow. Be professional and genuine.',
        character: { name: 'Prof. Emma', role: 'University Professor', avatar: '👩‍🏫', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Intermediate',
        duration: '8 min',
        xp: 120,
        gradient: 'from-teal-600 to-emerald-750',
        skills: ['Negotiation', 'Persuasion', 'Professional tone'],
      },
      {
        id: 'campus_project_discussion',
        worldId: 'campus',
        num: 4,
        title: 'Discuss Project with Professor',
        desc: 'Present and defend your final project proposal to Professor Emma. Explain your idea, methodology, and expected outcomes.',
        character: { name: 'Prof. Emma', role: 'Research Advisor', avatar: '👩‍🏫', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Intermediate',
        duration: '10 min',
        xp: 130,
        gradient: 'from-emerald-500 to-teal-600',
        skills: ['Technical explanation', 'Critical thinking', 'Academic vocabulary'],
      },
      {
        id: 'campus_group_discussion',
        worldId: 'campus',
        num: 5,
        title: 'Group Discussion',
        desc: 'Participate in a moderated group discussion on "Should AI replace human teachers?" Defend your position with clear arguments.',
        character: { name: 'Ryan (Moderator)', role: 'Discussion Moderator', avatar: '👨‍🎓', bg: 'bg-teal-50', text: 'text-teal-700', ring: 'ring-teal-200' },
        difficulty: 'Intermediate',
        duration: '10 min',
        xp: 130,
        gradient: 'from-teal-600 to-emerald-700',
        skills: ['Critical thinking', 'Argumentation', 'Confidence'],
      },
      {
        id: 'campus_seminar_presentation',
        worldId: 'campus',
        num: 6,
        title: 'Seminar Presentation',
        desc: 'Present your research topic to Professor Emma in a formal seminar setting. Answer challenging questions from the evaluator.',
        character: { name: 'Prof. Emma', role: 'Senior Faculty', avatar: '👩‍🏫', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Advanced',
        duration: '12 min',
        xp: 160,
        gradient: 'from-emerald-600 to-green-700',
        skills: ['Public speaking', 'Deep knowledge', 'Academic formality'],
      },
      {
        id: 'campus_research_proposal',
        worldId: 'campus',
        num: 7,
        title: 'Research Proposal Discussion',
        desc: 'Defend your PhD or undergraduate research proposal to Professor Emma. Justify your methodology and contribution.',
        character: { name: 'Prof. Emma', role: 'Research Supervisor', avatar: '👩‍🏫', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Advanced',
        duration: '12 min',
        xp: 180,
        gradient: 'from-teal-650 to-emerald-750',
        skills: ['Research communication', 'Methodology', 'Academic rigor'],
      },
      {
        id: 'campus_final_viva',
        worldId: 'campus',
        num: 8,
        title: 'Final Viva Conversation',
        desc: 'Face your Final Viva Voce with Chief Examiner Professor Emma. Summarise your work and defend every aspect of your thesis.',
        character: { name: 'Prof. Emma', role: 'Chief Examiner', avatar: '👩‍🏫', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Advanced',
        duration: '15 min',
        xp: 220,
        gradient: 'from-emerald-700 to-green-800',
        skills: ['Thesis defence', 'Critical reflection', 'Composure under pressure'],
      },
    ],
  },
  workplace: {
    id: 'workplace',
    title: 'Workplace World',
    emoji: '💼',
    worldNumber: 2,
    subtitle: 'Navigate professional conversations with managers, clients, and colleagues.',
    gradient: 'from-emerald-600 via-teal-700 to-green-800',
    glow: 'shadow-emerald-500/25',
    accentColor: '#059669',
    championLabel: 'Workplace Pro',
    championThreshold: 3,
    totalXPLabel: '660 XP',
    returnPath: '/communication/workplace',
    coachTip: 'Workplace communication requires assertiveness and clarity. Focus on keeping your updates crisp, presenting data-backed reasons, and alignment on goals.',
    missions: [
      {
        id: 'workplace_standup',
        worldId: 'workplace',
        num: 1,
        title: 'Team Standup Meeting',
        desc: 'Deliver a crisp standup update to Ryan, your Agile Project Manager. Focus on status updates and blocker articulation.',
        character: { name: 'Ryan', role: 'Agile Project Manager', avatar: '👨‍💻', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Beginner',
        duration: '5 min',
        xp: 80,
        gradient: 'from-emerald-500 to-teal-600',
        skills: ['Conciseness', 'Status reporting', 'Blocker articulation'],
      },
      {
        id: 'workplace_feedback',
        worldId: 'workplace',
        num: 2,
        title: 'Ask for Feedback',
        desc: 'Proactively seek developmental feedback from David, your Engineering Manager. Learn to receive advice gracefully.',
        character: { name: 'David', role: 'Engineering Manager', avatar: '👔', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Beginner',
        duration: '6 min',
        xp: 90,
        gradient: 'from-teal-500 to-emerald-600',
        skills: ['Proactive feedback', 'Listening skills', 'Growth mindset'],
      },
      {
        id: 'workplace_performance_review',
        worldId: 'workplace',
        num: 3,
        title: 'Performance Review',
        desc: 'Prepare for formal performance evaluations with Director David. Articulate achievements and career goals.',
        character: { name: 'David', role: 'Engineering Director', avatar: '👔', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Intermediate',
        duration: '12 min',
        xp: 130,
        gradient: 'from-teal-650 to-emerald-750',
        skills: ['Value articulation', 'Receptiveness', 'Goal alignment'],
      },
      {
        id: 'workplace_salary_negotiation',
        worldId: 'workplace',
        num: 4,
        title: 'Salary Negotiation',
        desc: 'Negotiate your compensation package with Hirer David. Justify salary levels based on contributions.',
        character: { name: 'David', role: 'Hiring Director', avatar: '👔', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Advanced',
        duration: '12 min',
        xp: 180,
        gradient: 'from-emerald-650 to-green-700',
        skills: ['Salary negotiation', 'Market justification', 'Assertiveness'],
      },
      {
        id: 'workplace_client_presentation',
        worldId: 'workplace',
        num: 5,
        title: 'Client Presentation',
        desc: 'Present deliverables and handle scope change questions from Sophia, a demanding client.',
        character: { name: 'Sophia', role: 'Enterprise Client', avatar: '🤝', bg: 'bg-teal-50', text: 'text-teal-700', ring: 'ring-teal-200' },
        difficulty: 'Advanced',
        duration: '15 min',
        xp: 200,
        gradient: 'from-emerald-700 to-green-850',
        skills: ['Client communication', 'Demo presentation', 'Scope negotiation'],
      },
    ],
  },
  social: {
    id: 'social',
    title: 'Social World',
    emoji: '🤝',
    worldNumber: 3,
    subtitle: 'Build the confidence to connect with anyone — from small talk at a party to pitching your startup idea to a potential co-founder.',
    gradient: 'from-teal-600 via-cyan-700 to-emerald-800',
    glow: 'shadow-teal-500/25',
    accentColor: '#0d9488',
    championLabel: 'Social Champion',
    championThreshold: 3,
    totalXPLabel: '610 XP',
    returnPath: '/communication/social',
    coachTip: 'Social conversations feel natural when you stop trying to impress and start trying to connect. Focus on listening actively and asking follow-up questions.',
    missions: [
      {
        id: 'social_self_introduction',
        worldId: 'social',
        num: 1,
        title: 'Self Introduction',
        desc: 'Introduce yourself confidently to Ryan, a senior developer you just met at a professional networking event. Make a great first impression.',
        character: { name: 'Ryan', role: 'Senior Developer', avatar: '👨‍💻', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Beginner',
        duration: '5 min',
        xp: 80,
        gradient: 'from-emerald-500 to-teal-600',
        skills: ['First impressions', 'Self-branding', 'Confidence'],
      },
      {
        id: 'social_small_talk',
        worldId: 'social',
        num: 2,
        title: 'Small Talk',
        desc: "You're waiting for a meeting to start and strike up a casual conversation with Sophia, a colleague from another team you've never spoken to.",
        character: { name: 'Sophia', role: 'Product Designer', avatar: '👩‍🎨', bg: 'bg-teal-50', text: 'text-teal-700', ring: 'ring-teal-200' },
        difficulty: 'Beginner',
        duration: '5 min',
        xp: 80,
        gradient: 'from-teal-500 to-emerald-600',
        skills: ['Small talk', 'Active listening', 'Rapport building'],
      },
      {
        id: 'social_networking',
        worldId: 'social',
        num: 3,
        title: 'Networking Event',
        desc: 'At a tech meetup, approach Ryan — a senior engineer at a company you admire. Exchange ideas and make a connection.',
        character: { name: 'Ryan', role: 'Senior Developer', avatar: '👨‍💻', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Intermediate',
        duration: '8 min',
        xp: 120,
        gradient: 'from-teal-650 to-emerald-750',
        skills: ['Networking', 'Elevator pitch', 'Contact exchange'],
      },
      {
        id: 'social_asking_for_help',
        worldId: 'social',
        num: 4,
        title: 'Asking for Help',
        desc: "You're stuck on a complex algorithm problem. Approach Professor Emma — your faculty mentor — and ask for guidance without seeming helpless.",
        character: { name: 'Prof. Emma', role: 'Faculty Mentor', avatar: '👩‍🏫', bg: 'bg-teal-50', text: 'text-teal-700', ring: 'ring-teal-200' },
        difficulty: 'Intermediate',
        duration: '8 min',
        xp: 130,
        gradient: 'from-emerald-500 to-teal-600',
        skills: ['Asking for help', 'Clarity', 'Vulnerability with confidence'],
      },
      {
        id: 'social_founder_pitch',
        worldId: 'social',
        num: 5,
        title: 'Pitch a Co-founder',
        desc: 'Convince Sophia — a talented full-stack engineer — to join your early-stage startup as a technical co-founder.',
        character: { name: 'Sophia', role: 'Full-Stack Engineer', avatar: '🤝', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Advanced',
        duration: '10 min',
        xp: 200,
        gradient: 'from-emerald-600 to-green-800',
        skills: ['Venture pitching', 'Vision setting', 'Objection handling'],
      },
    ],
  },
  leadership: {
    id: 'leadership',
    title: 'Leadership World',
    emoji: '🎤',
    worldNumber: 4,
    subtitle: 'Command a room with authority. Practice leading teams, delivering feedback, making hard decisions, speaking publicly, and managing crises.',
    gradient: 'from-green-600 via-emerald-700 to-teal-800',
    glow: 'shadow-green-500/25',
    accentColor: '#16a34a',
    championLabel: 'Leadership Master',
    championThreshold: 3,
    totalXPLabel: '880 XP',
    returnPath: '/communication/leadership',
    coachTip: "Great leaders don't dominate conversations — they shape them. Practice being direct, clear, and empathetic.",
    missions: [
      {
        id: 'leadership_team_meeting',
        worldId: 'leadership',
        num: 1,
        title: 'Lead a Team Meeting',
        desc: 'Facilitate a critical sprint planning meeting with Tech Lead Ryan. Drive team alignment and decision making.',
        character: { name: 'Ryan', role: 'Tech Lead', avatar: '👨‍💻', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Intermediate',
        duration: '10 min',
        xp: 130,
        gradient: 'from-emerald-500 to-teal-600',
        skills: ['Meeting facilitation', 'Decision making', 'Team alignment'],
      },
      {
        id: 'leadership_giving_feedback',
        worldId: 'leadership',
        num: 2,
        title: 'Giving Feedback',
        desc: 'Deliver constructive performance feedback to mid-level engineer Ryan in an empathetic growth-focused way.',
        character: { name: 'Ryan', role: 'Mid-Level Engineer', avatar: '👨‍💻', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Intermediate',
        duration: '8 min',
        xp: 140,
        gradient: 'from-teal-500 to-emerald-600',
        skills: ['Constructive feedback', 'Empathy', 'Directness', 'Growth framing'],
      },
      {
        id: 'leadership_townhall',
        worldId: 'leadership',
        num: 3,
        title: 'Town Hall Speech',
        desc: 'Address your entire team and answer tough representative questions from Ryan.',
        character: { name: 'Ryan', role: 'Employee Representative', avatar: '👨‍💻', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Advanced',
        duration: '12 min',
        xp: 180,
        gradient: 'from-teal-650 to-emerald-750',
        skills: ['Town hall address', 'Transparency', 'Motivational speaking'],
      },
      {
        id: 'leadership_vc_pitch',
        worldId: 'leadership',
        num: 4,
        title: 'Pitch VCs for Funding',
        desc: 'Defend your business valuation, product traction, and strategy under VC partner David\'s scrutiny.',
        character: { name: 'David', role: 'Managing Director, VC Fund', avatar: '👔', bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' },
        difficulty: 'Advanced',
        duration: '15 min',
        xp: 220,
        gradient: 'from-emerald-650 to-green-700',
        skills: ['Investor pitching', 'Value estimation', 'Composure'],
      },
      {
        id: 'leadership_crisis',
        worldId: 'leadership',
        num: 5,
        title: 'Crisis Communication',
        desc: 'Address your executive team during a major production outage. State accountability and mitigation actions to Sophia.',
        character: { name: 'Sophia', role: 'Chief Technology Officer', avatar: '👩‍💼', bg: 'bg-teal-50', text: 'text-teal-700', ring: 'ring-teal-200' },
        difficulty: 'Advanced',
        duration: '15 min',
        xp: 210,
        gradient: 'from-emerald-700 to-green-800',
        skills: ['Crisis communication', 'Accountability', 'Recovery planning', 'Composure'],
      },
    ],
  },
};

export const ALL_MISSIONS: MissionDef[] = Object.values(WORLDS_DATA).flatMap(w => w.missions);
