[providers]
  node = {}

[phases.setup]
  nixPkgs = [
    "chromium",
    "nss",
    "nspr",
    "atk",
    "alsa-lib",
    "cups",
    "libdrm",
    "expat",
    "xorg.libXcomposite",
    "xorg.libXdamage",
    "xorg.libXext",
    "xorg.libXfixes",
    "xorg.libXrandr",
    "mesa",
    "libxkbcommon",
    "pango",
    "cairo"
  ]

[variables]
  # Instruct Puppeteer not to download its own browser built-in during `npm install`
  PUPPETEER_SKIP_DOWNLOAD = "true"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
